# Intro to Pandas and Numpy

In [40]:
import numpy as np 
import pandas as pd

## Numpy

In [33]:
#standard array
arr1 = np.array([1,2,3,4,5])
print(arr1, "\n")

#array of zeros
arr2 = np.zeros(5)
print(arr2, "\n")

#3x3 matrix of 1s
arr3 = np.ones((3,3))
print(arr3, "\n")

#Every 2nd number from 0 - 10
arr4 = np.arange(0,10,2)
print(arr4, "\n")

#random 3x3 matrix
arr5 = np.random.rand(3,3)
print(arr5, "\n")

#the shape of arr1
print(arr1.shape, "\n")

#size of arr1
print(arr1.size, "\n")

#type of data in arr1
print(arr1.dtype, "\n")

#indexing 
print(arr1[0], "\n")
#slicing 
print(arr1[1:4])

[1 2 3 4 5] 

[0. 0. 0. 0. 0.] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[0 2 4 6 8] 

[[7.06793629e-01 4.49422946e-01 8.88616610e-01]
 [1.86019814e-01 9.10802004e-01 3.36629512e-01]
 [3.82087676e-04 6.00743145e-01 8.54813655e-01]] 

(5,) 

5 

int64 

1 

[2 3 4]


In [34]:
#adding arr1 and arr3
arr6 = arr1 + arr2
print(arr6, "\n")

#sum of all elemnts of arr1
print(np.sum(arr1), "\n")

#multiplying each element in array by 2 
arr7 = arr1 * 2 
print(arr7, "\n")

#arranging 9 elements are creating 3x3 array
arr8 = np.arange(9).reshape(3,3)
print(arr8, "\n")

[1. 2. 3. 4. 5.] 

15 

[ 2  4  6  8 10] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



In [27]:
#stacking arrays vertically 
arr9 = np.vstack((arr8, arr8))
print(arr9)

#splitting arrays
arr10, arr11 = np.split(arr9, 2)
print("\n",arr10, arr11,"\n")

#transpose
arr12 = arr8.T
print(arr12, "\n")

#Universal function (ufuncs)
arr13 = np.sin(arr1)
print(arr13)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 3 6]
 [1 4 7]
 [2 5 8]] 

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [36]:
#Fancy indexing 
#prints 0th, 2nd and 4th element of arr1
indicies = np.array([0,2,4])
print(arr1[indicies], "\n")

#Boolean indexing 
#will print all values in arr1 that are > 3
bool_arr = arr1 > 3 
print(arr1[bool_arr], "\n")

#Adding 10 to arr1
arr14 = arr1 + 10 
print(arr14, "\n")

#Broadcasting
arr15 = arr1 + np.array([[10], [20], [30], [40], [50]])
print(arr15 , "\n")

[1 3 5] 

[4 5] 

[11 12 13 14 15] 

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]] 



In [38]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

C = np.dot(A,B)
print(C)

[[19 22]
 [43 50]]


In [39]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


## Pandas

In [43]:
#Create Series from a list
s1 = pd.Series([1, 2, 3, 4, 5])

#Create Series from an Array
s2 = pd.Series(np.array([1, 2, 3, 4, 5]))

#Create Series from dictionary
s3 = pd.Series({'a': 1, 'b': 2, 'c': 3})

print(s3['a'], "\n")

print(s3[0], "\n")

print(s3[:2], "\n")

1 

1 

a    1
b    2
dtype: int64 



In [44]:
s4 = s1 + s2

s5 = s1*2

print(s1.sum())

#drop missing values
s6 = s1.dropna()

#fill missing values
s7 = s1.fillna(0)

print(s1.isnull())

15
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [45]:
#creating data drames 

#create dataframe from a dictionary

data = {'Name': ['Alice', 'Bob', 'Charlie'],
       'Age': [25, 30, 35]}

df1 = pd.DataFrame(data)

#Create DataFrame from a list of lists
data = [['Alice', 25], ['Bob', 30], ['Charlie. 35']]
df2 = pd.DataFrame(data, columns=['Name', 'Age'])

In [47]:
#Indexing and SLicing DataFrames 

#Label-based indexing 

print(df1.iloc[0,0], "\n")

#Slicing
print(df1[:2])

Alice 

    Name  Age
0  Alice   25
1    Bob   30


In [49]:
#Basic operations

#Sorting
df1_sorted = df1.sort_values(by = 'Age')
print(df1_sorted, "\n")

#Filtering 
df1_filtered = df1[df1['Age'] > 30]
print(df1_filtered, "\n")

#Selecting columns
names = df1['Name']
print(names, "\n")

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35 

      Name  Age
2  Charlie   35 

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object 



In [50]:
#Data Manipulation

#Adding a Column 

df1['Gender'] = ['Female', 'Male', 'Male']

#Deleting a column
del df1['Gender']

#Updating a Column 
df1['Age'] = df1['Age'] + 1

In [51]:
#Handling Missing Values 

# Drop missing values 
df1_cleaned = df1.dropna()

#Fill missing values 
df1_filled = df1.fillna(0)

#Check for missing values 
print(df1.isnull().any())

Name    False
Age     False
dtype: bool


In [54]:
#Data normalization(numerical values only)

#Min-Max normalization 
#df1_normalized = (df1 - df1.min()) / (df1.max() - df1.min())

#Standardization 
#df1_standardized = (df1 - df1.mean()) / df1.std()


In [53]:
#Data aggregation and grouping 

#Group by age and calculate mean age 

age_groups = df1.groupby('Age')
mean_age = age_groups['Age'].mean()

In [59]:
#Merging DataFrames

#Create sample DataFrames

left = pd.DataFrame({'key': ['K0', 'K1', 'K2'], 
                    'value': ['V0', 'V1', 'V3']})

right = pd.DataFrame({'key': ['K1', 'K2', 'K3'], 
                    'value': ['V1', 'V2', 'V3']})
print(left, "\n")
print(right, "\n")

#Inner Join 
inner_join = pd.merge(left, right, on = 'key', how = 'left')
print(inner_join, "\n")

#Left join 
left_join = pd.merge(left, right, on = 'key', how='left')
print(left_join, "\n")

#Right join 
right_join = pd.merge(left, right, on='key', how='right')
print(right_join, "\n")

#Outer join 
outer_join = pd.merge(left, right, on='key', how='outer')
print(outer_join, "\n")


  key value
0  K0    V0
1  K1    V1
2  K2    V3 

  key value
0  K1    V1
1  K2    V2
2  K3    V3 

  key value_x value_y
0  K0      V0     NaN
1  K1      V1      V1
2  K2      V3      V2 

  key value_x value_y
0  K0      V0     NaN
1  K1      V1      V1
2  K2      V3      V2 

  key value_x value_y
0  K1      V1      V1
1  K2      V3      V2
2  K3     NaN      V3 

  key value_x value_y
0  K0      V0     NaN
1  K1      V1      V1
2  K2      V3      V2
3  K3     NaN      V3 



In [62]:
#Joining DataFrames

#Create sample DataFrames 

left = pd.DataFrame({'value1': [1, 2, 3]}, index=['a', 'b', 'c'])
right = pd.DataFrame({'value2': [4, 5 ,6]}, index=['a', 'b', 'd'])

#Join based on index
join_df = left.join(right, how='inner')